//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekttest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.OrderRows = new HashSet<OrderRow>();
        }
    
        public int ArticleID { get; set; }
        public string Text { get; set; }
        public string UnitPrice { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<OrderRow> OrderRows { get; set; }
    }
}
